apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: hmpps-complexity-of-need
  annotations:
    kubernetes.io/change-cause: "<to be filled in deploy job command>"
spec:
  replicas: 2
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  selector:
    matchLabels:
      app: hmpps-complexity-of-need
  template:
    metadata:
      labels:
        app: hmpps-complexity-of-need
    spec:
      containers:
        - name: hmpps-complexity-of-need
          image: quay.io/hmpps/hmpps-complexity-of-need:latest
          imagePullPolicy: Always
          command: ['sh', '-c', 'bundle exec puma -p 3000 -C ./config/puma.rb --pidfile /tmp/server.pid']
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 60
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "50m"
          envFrom:
            - configMapRef:
                name: app-environment
            - secretRef:
                name: app-environment-secrets
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-instance-output
                  key: rds_instance_address
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-instance-output
                  key: database_password
            - name: POSTGRES_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-instance-output
                  key: database_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: rds-instance-output
                  key: database_username
            - name: DOMAIN_EVENTS_TOPIC_ARN
              valueFrom:
                secretKeyRef:
                  name: hmpps-domain-events-topic
                  key: topic_arn
