apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: hmpps-complexity-of-need-staging-blue
    external-dns.alpha.kubernetes.io/aws-weight: "0"
    # Only allow incoming traffic from: other apps running in the MOJ Cloud Platform, and the MOJ Digital VPN
    nginx.ingress.kubernetes.io/whitelist-source-range: "35.178.209.113/32,3.8.51.207/32,35.177.252.54/32,81.134.202.29/32"
spec:
  tls:
  - hosts:
    - hmpps-complexity-of-need-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
  - hosts:
    - complexity-of-need-preprod.hmpps.service.justice.gov.uk
    secretName: preprod-cert
  rules:
  - host: hmpps-complexity-of-need-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: app-service
          servicePort: 3000
  - host: complexity-of-need-preprod.hmpps.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: app-service
          servicePort: 3000
