# Define non-sensitive environment variables that can be publicly known in this file
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-environment
data:
  RAILS_ENV: "production"
  SENTRY_CURRENT_ENV: "production"
  COMPLEXITY_OF_NEED_HOST: "https://complexity-of-need.hmpps.service.justice.gov.uk"
  NOMIS_OAUTH_HOST: "https://sign-in.hmpps.service.justice.gov.uk"
