apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: app-ingress-hmpps-complexity-of-need-production-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    # Only allow incoming traffic from: other apps running in the MOJ Cloud Platform, and the MOJ Digital VPN
    nginx.ingress.kubernetes.io/whitelist-source-range: "35.178.209.113/32,3.8.51.207/32,35.177.252.54/32,81.134.202.29/32"
spec:
  ingressClassName: default
  tls:
  - hosts:
    - hmpps-complexity-of-need-production.apps.live-1.cloud-platform.service.justice.gov.uk
  - hosts:
    - complexity-of-need.hmpps.service.justice.gov.uk
    secretName: production-cert
  rules:
  - host: hmpps-complexity-of-need-production.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: app-service
            port:
              number: 3000
  - host: complexity-of-need.hmpps.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: app-service
            port:
              number: 3000
