apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hmpps-complexity-of-need
  namespace: hmpps-complexity-of-need-staging
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: hmpps-complexity-of-need-staging-blue
    external-dns.alpha.kubernetes.io/aws-weight: "0"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - hmpps-complexity-of-need-staging.apps.live-1.cloud-platform.service.justice.gov.uk
  - hosts:
    - complexity-of-need-staging.hmpps.service.justice.gov.uk
    secretName: staging-cert
  rules:
  - host: hmpps-complexity-of-need-staging.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: hmpps-complexity-of-need
          servicePort: 3000
  - host: complexity-of-need-staging.hmpps.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: hmpps-complexity-of-need
          servicePort: 3000
