apiVersion: batch/v1
kind: Job
metadata:
  name: hmpps-complexity-of-need-migration
  labels:
    app: hmpps-complexity-of-need-migration
spec:
  ttlSecondsAfterFinished: 3600
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: hmpps-complexity-of-need-migration
          image: quay.io/hmpps/hmpps-complexity-of-need:latest
          imagePullPolicy: Always
          command: ['sh', '-c', 'bundle exec rails db:migrate && bundle exec rails db:seed']
          envFrom:
            - configMapRef:
                name: shared-environment
            - secretRef:
                name: hmpps-complexity-of-need-secrets
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: hmpps-complexity-of-need-rds-instance-output
                  key: postgres_host
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hmpps-complexity-of-need-rds-instance-output
                  key: postgres_password
            - name: POSTGRES_NAME
              valueFrom:
                secretKeyRef:
                  name: hmpps-complexity-of-need-rds-instance-output
                  key: postgres_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: hmpps-complexity-of-need-rds-instance-output
                  key: postgres_user
          resources:
            limits:
              memory: "1Gi"
              cpu: "50m"
            requests:
              memory: "1Gi"
              cpu: "30m"
      restartPolicy: Never
  backoffLimit: 4
