apiVersion: v1
kind: Secret
metadata:
  name: hmpps-complexity-of-need-secrets
type: Opaque
data:
  SECRET_KEY_BASE: YWIyOWM0ZDY0Y2M2MmY0YmU2ODNkYzEzZjRkZWQ2ODQ3OTNjYWY1NmEzYjQ1YmEwMTdiNWU5NjdhMzc1NzI5YWYzOWRjMTFkYzFlNjU5ODg2MmJiYTRkMTI2NjIzMDBmMzA3ZWYyYjg1MmI5YWE1MTQxMGU3NTZlZWVkN2RmMjg=
